[tox]
envlist =
    python3.10
    python3.11
    python3.12
    python3.13
isolated_build = True
skip_missing_interpreters = True

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
deps =
    coverage
commands =
    coverage run --data-file=.coverage.doc.tests --source=osmfinder -m pytest -v -s --durations=20 --doctest-modules --doctest-continue-on-failure osmfinder
    coverage run --data-file=.coverage.base.tests --source=osmfinder -m pytest -v -s --durations=20 tests
    coverage combine
    coverage xml -o coverage.{envname}.xml
    coverage report -m
