name: "Build & publish - PROD"
on:
  release:
    types: [released]

jobs:
  run-tests:
    name: "Run tests job"
    uses: ./.github/workflows/_tests.yml
    secrets: inherit

  build-n-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build
        run: uv build
      - name: Publish distribution 📦 to PyPI
        run: uv publish --verbose
